package com.mrfloris.exportbook;

/** Explicit fault-injection boundaries in the durable publication protocol. */
enum PublicationBoundary {
    PREPARED_DURABLE,
    BACKUP_FILE_COMMITTED,
    BACKUP_CREATED_DURABLE,
    LIVE_FILE_COMMITTED,
    LIVE_COMMITTED_DURABLE,
    MANIFEST_CHECKPOINT_COMMITTED,
    MANIFEST_CHECKPOINTED_DURABLE,
    ARCHIVE_FILE_COMMITTED,
    ARCHIVE_CREATED_DURABLE,
    STAGED_FILE_REMOVED,
    STAGED_REMOVED_DURABLE,
    HISTORY_MANIFEST_CREATED,
    ACTIVE_MANIFEST_REMOVED,
    MANIFEST_FINALIZED,
    FINALIZED_DURABLE,
    JOURNAL_DELETED
}
